// Block types: p, h (subheading), ul, ol, code, out (output), table, flow
export const sections = [
{ id:'http-methods', group:'Theory', title:'HTTP Methods', blocks:[
['p','HTTP (HyperText Transfer Protocol) is a communication protocol used for transferring information between a client and a server over the web. HTTP methods define the type of operation that the client wants the server to perform.'],
['p','When a client sends a request to a server, the HTTP method tells the server what action should be performed on the requested resource.'],
['p','The commonly used HTTP methods are GET, POST, PUT, and DELETE.'],
['h','1. GET Method'],
['p','The GET method is used to request or retrieve data from a server.'],
['p','It is mainly used when the client wants to read existing information. The GET request does not normally modify the data stored on the server.'],
['p','Example:'],['code','GET /products'],
['p','This request asks the server to return a list of products.'],
['p','Uses:'],['ul',['Retrieving product information','Displaying user details','Fetching records from a database','Searching or viewing information']],
['h','2. POST Method'],
['p','The POST method is used to send data to the server. It is commonly used to create a new resource or submit information.'],
['p','The data is generally sent inside the body of the HTTP request.'],
['p','Example:'],['code','POST /products'],
['p','For example, when a user adds a new product, the product details can be sent to the server using a POST request.'],
['p','Uses:'],['ul',['Creating new records','Submitting forms','Registering a new user','Sending data to a server']],
['h','3. PUT Method'],
['p','The PUT method is used to update or replace existing data on the server.'],
['p','It is generally used when the client wants to modify an existing resource.'],
['p','Example:'],['code','PUT /products/10'],
['p','Here, the request can be used to update the product having ID 10.'],
['p','Uses:'],['ul',['Updating user information','Updating product details','Modifying existing records']],
['h','4. DELETE Method'],
['p','The DELETE method is used to remove a resource from the server.'],
['p','It tells the server that the specified resource should be deleted.'],
['p','Example:'],['code','DELETE /products/10'],
['p','Here, the request asks the server to delete the product having ID 10.'],
['p','Uses:'],['ul',['Deleting products','Removing user records','Deleting unwanted data']],
['h','Comparison of HTTP Methods'],
['table',[['HTTP Method','Main Purpose'],['GET','Retrieve or read data'],['POST','Send or create new data'],['PUT','Update or replace existing data'],['DELETE','Remove existing data']]],
['h','Advantages of HTTP Methods'],
['ol',['They provide a standard way for clients and servers to communicate.','They clearly define the operation to be performed.','They are widely used in web applications and APIs.','They make data operations such as retrieving, creating, updating, and deleting easier to manage.']],
['h','Conclusion'],
['p','HTTP methods are an important part of web communication. They define different operations between a client and a server. The four commonly used methods are GET, POST, PUT, and DELETE, which are used for retrieving, creating, updating, and deleting data respectively.']
]},
{ id:'react-lifecycle', group:'Theory', title:'React Lifecycle', blocks:[
['p','The React Lifecycle refers to the different stages through which a React component passes during its existence.'],
['p','A component is created, displayed on the screen, updated when its data changes, and finally removed from the screen.'],
['p','The React component lifecycle is mainly divided into three phases:'],
['ol',['Mounting','Updating','Unmounting']],
['h','1. Mounting Phase'],
['p','The Mounting phase is the first phase of the React component lifecycle.'],
['p','It occurs when a component is created and inserted into the DOM for the first time.'],
['p','During mounting:'],['ul',['The component is created.','Initial properties and state are initialized.','The component is rendered.','The component appears on the screen.']],
['p','In simple words, Mounting means the component is being created and displayed for the first time.'],
['p','Example:'],
['p','When a React application starts and a component such as Home is displayed for the first time, the component goes through the mounting phase.'],
['h','2. Updating Phase'],
['p',"The Updating phase occurs when the component's state or props change."],
['p','React detects the change and re-renders the component so that the updated information can be displayed.'],
['p','Updating can occur because of:'],['ul',['Changes in state','Changes in props','User interaction','Changes in data']],
['p','For example, if a button changes a counter from 1 to 2, the component is updated and React displays the new value.'],
['p','In simple words, Updating means changing and re-rendering an already existing component.'],
['h','3. Unmounting Phase'],
['p','The Unmounting phase is the final phase of the React lifecycle.'],
['p','It occurs when a component is removed from the DOM.'],
['p','Before a component is removed, cleanup operations may need to be performed. For example, unnecessary resources or processes associated with the component can be cleaned up.'],
['p','In React class components, the:'],['code','componentWillUnmount()'],
['p','method is used before the component is removed from the DOM.'],
['p','It can be used for cleanup activities.'],
['p','Example:'],['code','componentWillUnmount() {\n   // cleanup operation\n}'],
['p','In simple words, Unmounting means removing the component from the screen and performing necessary cleanup.'],
['h','React Lifecycle Flow'],
['p','The complete lifecycle can be represented as:'],
['p','Mounting → Updating → Unmounting'],
['flow',[['Mounting','Component is created and displayed.'],['Updating','Component changes because of state or props updates.'],['Unmounting','Component is removed from the DOM.']]],
['h','Importance of React Lifecycle'],
['p','The React lifecycle is important because:'],
['ol',['It helps developers understand how a component behaves.','It allows operations to be performed at the appropriate stage.','It helps manage changes in state and props.','It allows cleanup operations before a component is removed.','It helps in managing the overall behavior of React components.']],
['h','Conclusion'],
['p','The React Lifecycle describes the complete journey of a component from creation to removal. It consists of Mounting, Updating, and Unmounting phases. Understanding these phases helps developers properly manage component rendering, updates, and cleanup operations.']
]},
{ id:'react-hooks', group:'Theory', title:'React Hooks', blocks:[
['p',"React Hooks are functions introduced in React 16.8 that allow us to use state and other React features in functional components without writing a class. Hooks connect functional components with React's state and lifecycle features."],
['p','Some commonly used Hooks are useState, useEffect, useContext, useMemo and useRef.'],
['h','useState()'],
['p','useState() is used to declare and manage state in a functional component. It returns the current state value and a function used to update that value.'],
['p','Example:'],['code','const [count, setCount] = useState(0);'],
['p','Here, count is the state value and setCount is used to update it.'],
['h','useEffect()'],
['p','useEffect() is used to perform side effects in functional components. It can be used for operations such as fetching data from an API or performing actions after rendering.'],
['p','Example:'],['code','useEffect(() => { ... }, []);'],
['h','Rules of Hooks'],
['ol',['Hooks should be called only at the top level.','Hooks should be called only from React functions or custom Hooks.']],
['p','Thus, Hooks make functional components more powerful and easier to use.']
]},
{ id:'nodejs', group:'Theory', title:'Node.js', blocks:[
['p','Node.js is an open-source and cross-platform JavaScript runtime environment. It runs the V8 JavaScript engine outside the browser and is mainly used for server-side and real-time applications.'],
['p','Node.js uses an event-driven and non-blocking I/O model, which makes it lightweight and efficient for data-intensive applications.'],
['h','Features of Node.js'],
['ol',["Extremely Fast: Node.js is built on Google's V8 JavaScript Engine, which provides fast code execution.",'Single-threaded: It follows a single-threaded model with event looping.','Highly Scalable: Its event mechanism allows the server to respond in a non-blocking way.','No Buffering: Node.js applications output data in chunks instead of buffering the complete data.','Open Source: It has a large open-source community and many available modules.']],
['p','Therefore, Node.js is suitable for developing fast and scalable network applications.']
]},
{ id:'node-modules', group:'Theory', title:'Node.js Modules', blocks:[
['p','A module in Node.js can be considered similar to a JavaScript library. It is a set of functions that can be included and reused in an application.'],
['h','1. Built-in Modules'],
['p','Node.js provides several built-in modules that can be used without additional installation. The require() function is used to include a module.'],
['p','Example:'],['code',"var http = require('http');"],
['p','The HTTP module can then be used to create an HTTP server.'],
['h','2. Custom Modules'],
['p','Node.js also allows developers to create their own modules according to application requirements. The exports keyword is used to make properties and methods available outside the module.'],
['p','Example:'],['code','exports.myDateTime = function() {\n  return Date();\n};'],
['p','The custom module can be included using:'],['code',"var dt = require('./myfirstmodule');"],
['p','Here, ./ indicates that the module is located in the same folder.'],
['p','Thus, modules help in organizing and reusing code in Node.js applications.']
]},
{ id:'node-http', group:'Theory', title:'Node.js HTTP Module', blocks:[
['p','Node.js provides a built-in HTTP module that allows Node.js applications to transfer data over the Hyper Text Transfer Protocol (HTTP).'],
['p','The HTTP module can be included using the require() function:'],['code',"var http = require('http');"],
['p','It provides the createServer() method for creating an HTTP server.'],
['p','Example:'],['code',"var http = require('http');\nhttp.createServer(function(req, res) {\n  res.write('Hello World!');\n  res.end();\n}).listen(8080);"],
['h','Explanation'],
['ul',["require('http') includes the HTTP module.",'createServer() creates an HTTP server.','req represents the request from the client.','res represents the response sent to the client.','res.write() writes a response.','res.end() ends the response.','listen(8080) makes the server listen on port 8080.']],
['p','Thus, the HTTP module is used to create basic web servers in Node.js.']
]},
{ id:'lists-keys', group:'Theory', title:'Lists and Keys in React', blocks:[
['p','Lists are commonly used in React applications to display multiple items such as menus, tasks, pictures or shopping items.'],
['p','In JavaScript, the map() method is used to iterate through an array and create a new array. React commonly uses map() to display lists.'],
['p','Keys are special string attributes used when creating lists of elements in React. Keys help React identify which items have been changed, updated or deleted.'],
['p','Example:'],['code','const numbers = [1, 2, 3, 4, 5];\nconst updatedNums = numbers.map((number, index) =>\n  <li key={index}>{number}</li>\n);'],
['p','A key should uniquely identify an item among its siblings. Usually, an ID is preferred as a key.'],
['p','Using array indexes as keys is discouraged when list elements may be reordered because the keys can change.'],
['p','Thus, lists help display multiple items, while keys help React efficiently identify individual list elements.']
]},
{ id:'events', group:'Theory', title:'Event Handling in React', blocks:[
['p','An event is an action triggered by a user or the system, such as a mouse click, pressing a key, loading a web page or resizing a window.'],
['p',"React has its own event handling system called Synthetic Events. A Synthetic Event is a cross-browser wrapper around the browser's native event."],
['h','Important differences in React Events'],
['ol',['React event names use camelCase, such as onClick.','In JSX, a function is passed as the event handler instead of a string.','preventDefault() is used to prevent the default behaviour of an event.']],
['p','Example:'],['code','<button onClick={showMessage}>\n  Hello World\n</button>'],
['p','Here, onClick calls the showMessage function when the button is clicked.'],
['p','Thus, React event handling allows components to respond to user interactions effectively.']
]},
{ id:'web-frameworks', group:'Theory', title:'Web Frameworks', blocks:[
['p','A Web Framework provides a structure and tools for developing web applications. It helps developers build applications more easily and reduces development effort.'],
['p','There are two main types of web frameworks:'],
['h','1. Server-Side Framework'],
['p','Server-side frameworks are used for developing the back-end of web applications. They run on the server and handle requests and application processing.'],
['p','Examples: .NET, Django, Ruby on Rails, Express and Symfony.'],
['h','2. Client-Side Framework'],
['p','Client-side frameworks are used on the client/browser side. They mainly help in developing the user interface and handling user interactions.'],
['p','Web frameworks provide a structured approach to application development and help reduce development time.'],
['p','Therefore, web frameworks are important for both client-side and server-side web application development.']
]},
{ id:'expressjs', group:'Theory', title:'Express.js', blocks:[
['p','Express.js is a web framework used with Node.js for developing server-side web applications and APIs. It provides a simple structure for handling client requests and server responses.'],
['h','Features of Express.js'],
['ol',['Routing: Express.js provides routing for handling different URLs and requests.','Middleware: It supports middleware functions for processing requests.','HTTP Methods: It can handle methods such as GET and POST.','API Development: Express.js can be used to develop APIs.','Simple and Flexible: It provides a simple structure for Node.js web application development.']],
['p','Express.js is therefore useful for creating server-side applications and APIs using Node.js.']
]},
{ id:'express-routing', group:'Theory', title:'Routing in Express.js', blocks:[
['p','Routing in Express.js defines how an application responds to a particular URL and HTTP request.'],
['h','GET Route'],
['p','The GET method is used to request or retrieve data.'],
['p','Example:'],['code',"app.get('/movies', (req, res) => {\n  res.send('Movie List');\n});"],
['p','When a client sends a GET request to /movies, the server returns the movie list.'],
['h','POST Route'],
['p','The POST method is used to send data to the server.'],
['p','Example:'],['code',"app.post('/movies', (req, res) => {\n  res.send('Movie added');\n});"],
['p','When a client sends a POST request to /movies, the server processes the submitted data.'],
['p','Thus, Express.js routing helps connect URLs and HTTP methods with specific server-side functions.']
]},
{ id:'prog-usestate', group:'ETT Notes Programs', title:'1. React useState()', blocks:[
['p','App.js'],
['code',"import React, { useState } from 'react';\n\nfunction CountApp() {\n  const [count, setCount] = useState(0);\n\n  return (\n    <div>\n      <p>You clicked {count} times</p>\n\n      <button onClick={() => setCount(count + 1)}>\n        click me\n      </button>\n    </div>\n  );\n}\n\nexport default CountApp;"],
['p','Output'],['p','Initially:'],['out','You clicked 0 times\n[ click me ]'],
['p','After clicking 3 times:'],['out','You clicked 3 times\n[ click me ]'],
['p','Exam mein important: useState(0) state ko initialize karta hai aur setCount() state update karta hai.']
]},
{ id:'prog-useeffect', group:'ETT Notes Programs', title:'2. React useEffect()', blocks:[
['p','App.js'],
['code',"import React, { useState, useEffect } from 'react';\n\nfunction CounterExample() {\n  const [count, setCount] = useState(0);\n\n  useEffect(() => {\n    document.title = `You clicked ${count} times`;\n  });\n\n  return (\n    <div>\n      <p>You clicked {count} times</p>\n\n      <button onClick={() => setCount(count + 1)}>\n        Click me\n      </button>\n    </div>\n  );\n}\n\nexport default CounterExample;"],
['p','Output'],['p','Initially:'],['out','You clicked 0 times\n[ Click me ]'],
['p','After clicking 2 times:'],['out','You clicked 2 times\n[ Click me ]'],
['p','Browser tab title also becomes:'],['out','You clicked 2 times']
]},
{ id:'prog-fetch', group:'ETT Notes Programs', title:'3. React — Fetch Data from API', blocks:[
['p','App.js'],
['code',"import React from \"react\";\nimport './App.css';\n\nclass App extends React.Component {\n\n  constructor(props) {\n    super(props);\n\n    this.state = {\n      items: [],\n      DataisLoaded: false\n    };\n  }\n\n  componentDidMount() {\n\n    fetch(\"https://jsonplaceholder.typicode.com/users\")\n      .then((res) => res.json())\n      .then((json) => {\n\n        this.setState({\n          items: json,\n          DataisLoaded: true\n        });\n\n      });\n  }\n\n  render() {\n\n    const { DataisLoaded, items } = this.state;\n\n    if (!DataisLoaded)\n      return <div>\n        <h1> Please wait some time.... </h1>\n      </div>;\n\n    return (\n      <div className=\"App\">\n        <h1>Fetch data from an api in react</h1>\n        {\n          items.map((item) => (\n            <ol key={item.id}>\n              User_Name: {item.username},\n              Full_Name: {item.name},\n              User_Email: {item.email}\n            </ol>\n          ))\n        }\n      </div>\n    );\n  }\n}\n\nexport default App;"],
['p','Output'],
['out','Fetch data from an API in react\n\nUser_Name: Bret\nFull_Name: Leanne Graham\nUser_Email: Sincere@april.biz\n\nUser_Name: Antonette\nFull_Name: Ervin Howell\nUser_Email: Shanna@melissa.tv\n\nUser_Name: Samantha\nFull_Name: Clementine Bauch\nUser_Email: Nathan@yesenia.net\n\nUser_Name: Karianne\nFull_Name: Patricia Lebsack\nUser_Email: Julianne.OConner@kory.org'],
['p','And remaining users are displayed similarly.'],['p','This one is VERY important.']
]},
{ id:'prog-custom-module', group:'ETT Notes Programs', title:'4. Node.js — Custom Module', blocks:[
['p','File 1: myfirstmodule.js'],
['code','exports.myDateTime = function () {\n  return Date();\n};'],
['p','File 2: demo_module.js'],
['code',"var http = require('http');\n\nvar dt = require('./myfirstmodule');\n\nhttp.createServer(function (req, res) {\n\n  res.writeHead(200, {'Content-Type': 'text/html'});\n\n  res.write(\n    \"The date and time are currently: \" + dt.myDateTime()\n  );\n\n  res.end();\n\n}).listen(8080);"],
['p','Run'],['out','node demo_module.js'],
['p','Output'],['p','Browser:'],
['out','The date and time are currently:\nWed Oct 07 2026 22:00:00 GMT+0530 (India Standard Time)'],
['p','Note: Date/time actual system ke according change hoga.']
]},
{ id:'prog-http-server', group:'ETT Notes Programs', title:'5. Node.js — HTTP Server', blocks:[
['p','demo_http.js'],
['code',"var http = require('http');\n\n// Create a server object\nhttp.createServer(function (req, res) {\n\n  res.write('Hello World!');\n\n  res.end();\n\n}).listen(8080);"],
['p','Run'],['out','node demo_http.js'],
['p','Output'],['p','Browser mein:'],['out','Hello World!'],
['p','Server port:'],['out','http://localhost:8080']
]},
{ id:'prog-web-server', group:'ETT Notes Programs', title:'6. Node.js — Creating a Web Server', blocks:[
['p','server.js'],
['code',"const http = require('http');\n\nconst hostname = '127.0.0.1';\nconst port = 3000;\n\nconst server = http.createServer((req, res) => {\n\n  res.statusCode = 200;\n\n  res.setHeader('Content-Type', 'text/plain');\n\n  res.end('Hello World\\n');\n\n});\n\nserver.listen(port, hostname, () => {\n\n  console.log(\n    `Server running at http://${hostname}:${port}/`\n  );\n\n});"],
['p','Run'],['out','node server.js'],
['p','Terminal Output'],['out','Server running at http://127.0.0.1:3000/'],
['p','Browser Output'],['out','Hello World']
]},
{ id:'final-priority', group:'ETT Notes Programs', title:'FINAL PRIORITY — exam ke liye', blocks:[
['p','Agar bahut kam time hai, bas ye order follow kar:'],
['table',[['Priority','Program'],['1','React API Fetch'],['2','Node.js HTTP Server'],['3','React useState()'],['4','React useEffect()'],['5','Node.js Custom Module']]],
['p','Ye 5 pakka kar bhai. Ye directly tumhare ETT NOTES.pdf ke programs hain.']
]}
]
